face_detection:
  config: "models/face_detection/deploy.prototxt.txt"
  model: "models/face_detection/res10_300x300_ssd_iter_140000.caffemodel"
face_age:
  config: "models/face_age/age_deploy.prototxt"
  model: "models/face_age/age_net.caffemodel"
face_gender:
  config: "models/face_gender/gender_deploy.prototxt"
  model: "models/face_gender/gender_net.caffemodel"
face_landmarks:
  model: 'models/face_alignment/shape_predictor_68_face_landmarks.dat'
results_interpretation:
  Demographic predictions:
    age_range: "Predicted age"
    age_confidence: "Confidence of age prediction (0-1)"
    gender: "Predicted gender"
    gender_confidence: "Confidence of gender prediction (0-1)"
  Face proportions:
    top_of_nose_to_middle_of_mouth_vs_middle_mouth_to_bottom_of_chin: "Ideal value is 1.62 (golden ratio - from classical Greek work on maths and geometry)"
    middle_of_mouth_to_bottom_of_mouth_vs_top_of_mouth_to_middle_of_mouth: "Ideal value is 1.62 (golden ratio - from classical Greek work on maths and geometry)"
    eye_width_vs_distance_between_eyes: "Ideal value is 1"
    eye_to_eyebrows_vs_eye_height: "Ideal value is 1"
    center_of_left_to_right_eye_vs_mouth_width: "Ideal value is 1"
  Face symmetry metrics:
    structural_similarity: "Range: -1 (opposite) to 1 (similar). Considers differences in structural information, luminance, and texture."
    cosine_distance: "Ranges: -1 to 1. 0 =similar, -1 or 1 = not similar. Considers differences in pixels."
    mse: Lower means more similar. Minimum value is 0, maximum is unbounded. Measures pixel differences."
    mae:  Lower means more similar. Minimum value is 0, maximum is unbounded. Measures pixel differences."
    histogram_correlation: "Range: -1 (opposite) to 1 (similar). Considers similarity based on color or intensity distributions."
    histogram_intersection: "Range: 0 (similar) to total pixels in image (not similar). Consider similarity based on color or intensity distributions."
    orb_detector_matches: "Higher is better. Counts the number of matches between keypoints in images."
    pixel_difference: "Lower is better.  Minimum value is 0, maximum is unbounded."
  Face texture metrics:
    texture_std: "Lower means less varied facial texture. Minimum is 0, maximum is unbounded."
