face_detection:
  config: "models/face_detection/deploy.prototxt.txt"
  model: "models/face_detection/res10_300x300_ssd_iter_140000.caffemodel"
face_age:
  config: "models/face_age/age_deploy.prototxt"
  model: "models/face_age/age_net.caffemodel"
face_gender:
  config: "models/face_gender/gender_deploy.prototxt"
  model: "models/face_gender/gender_net.caffemodel"
face_landmarks:
  model: 'models/face_alignment/shape_predictor_68_face_landmarks.dat'
